spring:
    application:
      name: learn-graphql-java

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 90
  playground:
    enable: true #change in production environment
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account simple query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json


