spring:
    application:
      name: learn-graphql-java
    profiles:
      active: ${SPRING_BOOT_ACTIVE_PROFILE:local}

server:
  port: ${SPRING_BOOT_DEFAULT_PORT:8080}
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 90
    exception-handlers-enabled: false
  voyager:
    enable: true #change to false in a production environment
  playground:
    enable: true #change to false in production environment
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account simple query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json


